# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - hand_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1_21P0041_21P0240
      - joint2_21P0041_21P0240
      - joint3_21P0041_21P0240
      - joint4_21P0041_21P0240
      - joint5_21P0041_21P0240
      - joint6_21P0041_21P0240
  hand_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint7_21P0041_21P0240
      - joint8_21P0041_21P0240